### ISSUE TITLE
excuse me ! how you get the value of landmarks_3d_list,thanks

### ISSUE THREAD

**Issue by lc33851947** [qhan1028/Headpose-Detection#1]
up

**Comment by qhan1028** [comment]
I provided three 3D facial landmark sets in `landmarks_3d_list`,
and these value are not computed by myself but referenced from other codes.

1st set [link](https://www.learnopencv.com/head-pose-estimation-using-opencv-and-dlib/)
From the python code (line 21~29), and I scaled it into the same range as 2nd set.

2nd set [link](http://aifi.isr.uc.pt/Downloads/OpenGL/glAnthropometric3DModel.cpp) 
line 69.

3rd set
5 points selected from 2nd set.

**Comment by lc33851947** [comment]
thank you
